spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#    listener:
#      simple:
#        default-requeue-rejected: false

server:
  port: 8083